p = input('Digite algo: ')
print('O "algo" que você digitou foi {}'.format(p))
print('O que você digitou é {}'.format(type(p)))
print('O que você digitou só tem espaços? {} '.format(p.isspace()))
print('O que você digitou tem apenas letras? {} '.format(p.isalpha()))
print('O que você digitou tem apenas números? {} '.format(p.isnumeric()))
print('O que você digitou tem números e/ou letras? {} '.format(p.isalnum()))
print('O que você digitou tem todas as letras em maiúsculo? {} '.format(p.isupper()))
print('O que você digitou tem todas as letras em minúsculo? {} '.format(p.islower()))
print('O que você digitou é capitalizado? {} '.format(p.istitle()))
