e = input('Digite algo: ')
print('O "algo" que você digitou foi {}'.format(e))
print('O que você digitou é {}'.format(type(e)))
print('O que você digitou só tem espaços? {} '.format(e.isspace()))
print('O que você digitou tem apenas letras? {} '.format(e.isalpha()))
print('O que você digitou tem apenas números? {} '.format(e.isnumeric()))
print('O que você digitou tem números e/ou letras? {} '.format(e.isalnum()))
print('O que você digitou tem todas as letras em maiúsculo? {} '.format(e.isupper()))
print('O que você digitou tem todas as letras em minúsculo? {} '.format(e.islower()))
print('O que você digitou é capitalizado? {} '.format(e.istitle()))
